test_that("use", {
  expect_silent(check_python_package_name(package_name = "_libgcc_mutex"))
  expect_silent(check_python_package_name("_openmp_mutex"))
  expect_silent(check_python_package_name("ca-certificates"))
  expect_silent(check_python_package_name("certifi"))
  expect_silent(check_python_package_name("ld_impl_linux-64"))
  expect_silent(check_python_package_name("libblas"))
  expect_silent(check_python_package_name("libgfortran5"))
  expect_silent(check_python_package_name("libgcc-ng"))
  expect_silent(check_python_package_name("libstdcxx-ng"))
  expect_silent(check_python_package_name("python_abi"))
  expect_silent(check_python_package_name("xz"))
  expect_silent(check_python_package_name("tk"))
  expect_error(check_python_package_name(package_name = ""))
  expect_error(check_python_package_name(NA))
  expect_error(check_python_package_name(NULL))
  expect_error(check_python_package_name(Inf))
  expect_error(check_python_package_name(c()))
  expect_error(check_python_package_name(list()))
  expect_error(check_python_package_name(42))
  expect_error(check_python_package_name(3.14))
  expect_error(check_python_package_name(0))
  expect_error(check_python_package_name(character(0)))
  expect_error(check_python_package_name("tk==3.14"))
  expect_error(
    check_python_package_name(c("xz", "tk")),
    "'package_name' must be exactly one Python package name"
  )
})
